### ISSUE TITLE
help.search('token', package = 'rStrava') not working

### ISSUE THREAD

**Issue by elmiraberjisian** [fawda123/rStrava#65] opened 2019-09-11 16:31 UTC
I tried to run the first two lines you provided in README and it seems there is no results because the help window return No results found. I'm trying to know what information is public in Strava.
Thank you :)

**Comment by fawda123** [comment] 2019-09-13 15:50
This is an RStudio issue: https://github.com/rstudio/rstudio/issues/4819
 
The [preview version](https://www.rstudio.com/products/rstudio/download/preview/) (1.2.1578) has a fix for this.  I just downloaded and installed the preview version and everything works as intended.

**Closed** 2019-09-14 14:35 UTC
Labels: question
