### ISSUE TITLE
dplyr verbs do not preserve 'actframe' class or attributes

### ISSUE THREAD

**Issue by niklasvm** [fawda123/rStrava#40] opened 2018-07-08 13:00 UTC
Hi

Whilst working on the shiny-strava application I noticed that dplyr verbs do not preserve the 'actframe' class that is created when running ```compile_activities```.

Example:

```{r}
my_acts.df <- compile_activities(my_acts,acts = NULL,units = 'metric')
class(my_acts.df)
[1] "actframe"   "data.frame"

filtered_my_acts.df <- my_acts.df %>% 
  filter(type=='Run')

class(filtered_my_acts.df)
[1] "data.frame"

````

This makes it difficult to use functions such as ```get_heat_map```.
From what I've read, you seem to have to overload methods to cater for your own specific classes. Something of the form:

```{r}
filter.actframe <- function(.data,...) {
  
  # capture classes
  old_classes <- class(.data)
  
  # strip actframe class
  class(.data) <- old_classes[!old_classes == 'actframe']
  
  # perform operation
  .data <- .data %>% dplyr::filter(...)
  
  # add back actframe class
  class(.data) <- old_classes
  
  return(.data)
}
```

**Comment by fawda123** [comment] 2018-07-08 15:32
Yea that's a bit of a challenge, dplyr tends to override existing classes.  I like your approach of making a separate filter function.  

Alternatively, the `get_heat_map` function has an acts argument that specifies which activities to plot.  It's based on the index value in the list that's returned from `get_activity_list` (so, not an `actframe` object).  This also means you have to know which activities correspond to which list element, which is not ideal.  

The README file for rStrava shows how to select activities as input to `get_heat_map`:

```r
my_acts <- get_activity_list(stoken)
acts <- lapply(my_acts, function(x) x$location_city) %in% c('Pensacola', 'Pensacola Beach', 'Milton') 
get_heat_map(my_acts, acts = which(acts), col = 'darkgreen', size = 2, dist = F, f = 0.5)
```

Again, not an ideal solution.  Another option is to create default version of `get_heat_map` that works on data frames, also not ideal.  

I'm kind of liking your idea about a special filter function.  Want to submit a PR to the dev branch?

**Comment by niklasvm** [comment] 2018-07-08 17:45
Sounds good, I'll do that in the next few days. Thanks

**Comment by fawda123** [comment] 2018-07-09 16:43
For what it's worth, I took a stab at it today but hit some roadblocks with defining methods for dplyr generics.  I assume you've found the same threads ([here](https://stackoverflow.com/questions/41967700/defining-custom-dplyr-methods-in-r-package/41968721) and [here](https://github.com/tidyverse/dplyr/issues/719)) since your example looks similar.  

Anyway, you might use this code as a starting point.  I couldn't figure out a solution in the 30 minutes I spent on this.  The problem is getting it recognized as a dplyr method, among other things.  

```r
#' Filter
#'
#' Filter an actframe object
#'
#' @param act_data an activities list object returned by \code{\link{get_activity_list}} or a \code{data.frame} returned by \code{\link{compile_activities}}
#' @param ... a logocial vector passed to \code{\link[dplyr]{filter}} for filtering rows or list elements in \code{act_data} 
#'
#' @export
#' 
#' @importFrom dplyr filter_
#' 
#' @method filter_ actframe
#' 
#' @return An \code{actframe} object that excludes rows filtered by \code{...}
#' 
#' @examples 
#' \dontrun{
#' 
#' # get actframe, all activities
#' stoken <- httr::config(token = strava_oauth(app_name, app_client_id, app_secret, cache = TRUE))
#' my_acts <- get_activity_list(stoken)
#' act_data <- compile_activities(my_acts)
#' 
#' # filter
#' filter_(act_data, name %in% 'Morning Ride')
#' }
filter_.actframe <- function(act_data, ...) {

	# capture classes
	old_classes <- class(act_data)
	
	# strip actframe class
	class(act_data) <- old_classes[!old_classes == 'actframe']

	# perform operation
	act_data <- act_data %>% dplyr::filter_(...)
	
	# add back actframe class
	class(act_data) <- old_classes
	
	return(act_data)
	
}
```

**Comment by niklasvm** [comment] 2018-07-10 06:14
Thanks for the above. I've made a PR. The main use case is shown below:
```{r}

library(tidyverse)
library(rStrava)


my_acts <- get_activity_list(stoken)

acts_data <- compile_activities(my_acts)

filter.actframe <- function(.data,...) {
	
	# capture classes
	old_classes <- class(.data)
	
	# capture attributes
	unit_type <- attr(.data,'unit_type')
	unit_vals <- attr(.data,'unit_vals')
	
	# strip actframe class
	class(.data) <- old_classes[!old_classes == 'actframe']
	
	# perform operation
	.data <- .data %>% dplyr::filter(...)
	
	# add back actframe class
	class(.data) <- c('actframe',class(.data))
	attr(.data,'unit_type') <- unit_type
	attr(.data,'unit_vals') <- unit_vals
	
	return(.data)
}

mutate.actframe <- function(.data,...) {
	
	# capture classes
	old_classes <- class(.data)
	
	# capture attributes
	unit_type <- attr(.data,'unit_type')
	unit_vals <- attr(.data,'unit_vals')
	
	# strip actframe class
	class(.data) <- old_classes[!old_classes == 'actframe']
	
	# perform operation
	.data <- dplyr::mutate(.data,...)
	
	# add back actframe class
	class(.data) <- c('actframe',class(.data))
	attr(.data,'unit_type') <- unit_type
	attr(.data,'unit_vals') <- unit_vals
	
	return(.data)
}

# helper to tidy compiled activities
tidy_activities <- function(.data) {
	
	# cast dates
	date_cols <- str_subset(colnames(.data),'date')
	.data[date_cols] <-  .data[date_cols] %>% 
		map(~strptime(.x,'%Y-%m-%dT%H:%M:%SZ')) %>% 
		map(as.POSIXct)
	
	return(.data)
}

# filter and plot
acts_data %>%
	tidy_activities() %>% 
	filter(type=='Run') %>% 
	filter(start_date>=Sys.Date()-21) %>% 
	get_heat_map(dist = F)

```

**Comment by fawda123** [comment] 2018-07-10 15:49
Thanks Niklas, I merged this on the master branch too.  You're also a contributor now if you're cool with that! 5d183afca1c96ae4d47654f260ea1a5fda6ff818

**Closed by fawda123** 2018-07-10 15:49 UTC
Labels: enhancement

**Comment by niklasvm** [comment] 2018-07-10 16:37
Happy, thanks!
